import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { redirect } from 'next/navigation'
import Header from './_components/Header'
import { getServerSession } from 'next-auth'
import { authOptions } from './_lib/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  if (session == null || session.user == null) {
    // redirect("/api/auth/signin");
  }

  return (
    <html lang="en" className='h-full bg-slate-200 dark:bg-gray-950'>
      <body className={`${inter.className} flex min-h-screen flex-col items-stretch`}>
        <Header title='Materiale curs'></Header>
        {children}
      </body>
    </html>
  )
}
